@startuml fig_domain_model
title MovieLoggerのドメインモデル図

package 映画 {
  ' Movie MODEL '
  '' ValueObject ''
  object MovieObject {
    ID
  }
  object TmdbObject {
    ID
  }

  '' Movie Entity ''
  entity Movie {
    {static} 映画ID
    タイトル
    概要
    ポスター
    公開日
    上映時間
    シリーズ
    ジャンル
    {static} TMDb_ID
    作成日
    更新日

    作成()
    更新()
  }
  entity MovieNote {
    {static} 映画ID
    鑑賞状況
    評価
    ノート
  }


  ' Movie Note ' 
  ' ???


  ' Movie RELATION '
  Movie::映画ID "1" -[#Blue]- "1" MovieObject::ID
  Movie::TMDb_ID "1" -[#Blue]- "1" TmdbObject::ID

  MovieNote::映画ID "1" -[#Blue]- "1" MovieObject::ID


  package シリーズ {
    object MovieSeriesIdObject {
      {static} シリーズID
    }

    entity MovieSeries {
      {static} ID
      シリーズ名
      シリーズポスター
    }
  }

  MovieSeries "1" -- "*" Movie::シリーズ
  MovieSeries::ID "1" -- "1" MovieSeriesIdObject::シリーズID
}




package 鑑賞状況 {
  enum AppreciationStatus {
    Watched
    Wanna_Watch
  }

  AppreciationStatus "1" -- "1" MovieNote::鑑賞状況
}




package ジャンル {
  object GenreIdObject {
    {static} ジャンルID
  }
  object Genre {
    action
    adventure
    animation
    comedy
    crime
    documentary
    drama
    family
    fantasy
    history
    horror
    music
    mystery
    romance
    SF
    TV
    thriller
    war
    western
  }

  GenreIdObject -- Genre
  GenreIdObject::ジャンルID "*" -[#Red]- "*" Movie::ジャンル
}




package ポスター {
  object PosterObject {
    ポスターのパス
  }

  PosterObject::ポスターのパス "1" -- "1" Movie::ポスター
  MovieSeries::シリーズポスター "1" -- "1" PosterObject::ポスターのポス
}




package 単語 {
  class Word {
    対象
  }
}

@enduml
