@startuml fig_object

title Filmographyのオブジェクト図
left to right direction

rectangle 「ターミネーター2」を未鑑賞でマイリストにある {
  object 映画002 {
    タイトル: ターミネーター2
    概要: 未来からの抹殺兵器ターミネーターを破壊し...
    公開日: 1991/08/24
    上映時間: 137分
  }

  object 映画記録002 {
    鑑賞状況: 未鑑賞
    評価: -
    ノート: 評価高いから観たいな〜♪
  }

  object 映画ポスター002 {
    ポスターURL: terminator2.jpg
  }

  object 映画ジャンル201 {
    ジャンル名: アクション
  }

  object 映画ジャンル202 {
    ジャンル名: スリラー
  }

  object 映画ジャンル203 {
    ジャンル名: SF
  }

  object 映画シリーズ201 {
    シリーズ名: ターミネーターシリーズ
  }

  映画記録002 *-- 映画002

  映画002 *-- 映画ポスター002
  映画002 *-- 映画ジャンル201
  映画002 *-- 映画ジャンル202
  映画002 *-- 映画ジャンル203
  映画002 *-- 映画シリーズ201
}






rectangle 「ターミネーター」を2回鑑賞 {
  object 映画鑑賞101 {
    鑑賞媒体: Amazon Prime Video
    鑑賞日: 2020/01/01
  }

  object 映画鑑賞102 {
    鑑賞媒体: U-NEXT
    鑑賞日: 2020/02/01
  }

  object 映画001 {
    タイトル: ターミネーター
    概要: アメリカのとある街、深夜突如奇怪な放電と共に...
    公開日: 1985/05/04
    上映時間: 108分
  }

  object 映画記録001 {
    鑑賞状況: 鑑賞済み
    評価: 5/5
    ノート: あれやこれや
  }

  object 映画ポスター001 {
    ポスターURL: terminator.jpg
  }

  object 映画ジャンル101 {
    ジャンル名: アクション
  }

  object 映画ジャンル102 {
    ジャンル名: スリラー
  }

  object 映画ジャンル103 {
    ジャンル名: SF
  }

  object 映画シリーズ101 {
    シリーズ名: ターミネーターシリーズ
  }

  映画記録001 *-- 映画鑑賞101
  映画記録001 *-- 映画鑑賞102
  映画記録001 *-- 映画001

  映画001 *-- 映画ポスター001
  映画001 *-- 映画ジャンル101
  映画001 *-- 映画ジャンル102
  映画001 *-- 映画ジャンル103
  映画001 *-- 映画シリーズ101
}

@enduml
